In [1]:
#import libraries

#NUmber crunching
import pandas as pd
import numpy as np

#Plots and graphs
import matplotlib.pyplot as plt  

#Pre-processing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

#Model building
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression

%matplotlib inline

In [2]:
%cd D:\MSC\Trimester2\LabonML\Datasets

D:\MSC\Trimester2\LabonML\Datasets


In [3]:
dataset = pd.read_json('iris.json')

In [4]:
dataset.shape

(150, 5)

In [5]:
dataset.head()

sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [26]:
X = dataset.iloc[:, [0,1,2,3]].values
y = dataset['species']

ds_train, ds_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#ds_train, ds_test = train_test_split(dataset, test_size=0.2, random_state=0)
ds_train.shape, ds_test.shape

((120, 4), (30, 4))

In [27]:
ds_train.dtype

dtype('float64')

In [28]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
y_train = label_encoder.transform(y_train)
y_test = label_encoder.transform(y_test)

In [29]:
sc = StandardScaler()
ds_train = sc.fit_transform(ds_train)
ds_test = sc.transform(ds_test)

In [30]:
logreg = LogisticRegression(random_state = 0, solver='lbfgs', multi_class='multinomial')
logreg.fit(ds_train, y_train)

LogisticRegression(multi_class='multinomial', random_state=0)

In [31]:
y_pred = logreg.predict(ds_test)
# Predict probabilities
y_pred_prob=logreg.predict_proba(ds_test)

In [32]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [33]:
logreg.score(ds_test,y_test)

1.0

In [34]:
### Print results 
y_pred_prob = np.round(y_pred_prob, 2)
res = "{} | {} | {} | {} | {}".format("y_test", "y_pred", "Setosa(%)", "Versicolor(%)", "Virginica(%)\n")
res += "\n".join("{} | {} | {} | {} | {}".format(x, y, a, b, c) for x, y, a, b, c in zip(y_test, y_pred, y_pred_prob[:,0], y_pred_prob[:,1], y_pred_prob[:,2]))
print(res)

y_test | y_pred | Setosa(%) | Versicolor(%) | Virginica(%)
2 | 2 | 0.0 | 0.03 | 0.97
1 | 1 | 0.01 | 0.96 | 0.04
0 | 0 | 1.0 | 0.0 | 0.0
2 | 2 | 0.0 | 0.08 | 0.92
0 | 0 | 0.98 | 0.02 | 0.0
2 | 2 | 0.0 | 0.01 | 0.99
0 | 0 | 0.98 | 0.02 | 0.0
1 | 1 | 0.01 | 0.71 | 0.28
1 | 1 | 0.0 | 0.73 | 0.27
1 | 1 | 0.02 | 0.9 | 0.08
2 | 2 | 0.0 | 0.48 | 0.52
1 | 1 | 0.02 | 0.76 | 0.22
1 | 1 | 0.01 | 0.87 | 0.12
1 | 1 | 0.0 | 0.7 | 0.3
1 | 1 | 0.01 | 0.77 | 0.22
0 | 0 | 0.99 | 0.01 | 0.0
1 | 1 | 0.01 | 0.74 | 0.25
1 | 1 | 0.02 | 0.89 | 0.09
0 | 0 | 0.94 | 0.06 | 0.0
0 | 0 | 0.99 | 0.01 | 0.0
2 | 2 | 0.0 | 0.18 | 0.82
1 | 1 | 0.04 | 0.74 | 0.22
0 | 0 | 0.98 | 0.02 | 0.0
0 | 0 | 0.96 | 0.04 | 0.0
2 | 2 | 0.0 | 0.35 | 0.65
0 | 0 | 1.0 | 0.0 | 0.0
0 | 0 | 0.99 | 0.01 | 0.0
1 | 1 | 0.02 | 0.88 | 0.1
1 | 1 | 0.08 | 0.91 | 0.01
0 | 0 | 0.97 | 0.03 | 0.0
